site_name: Compiladores (G16)
theme:
  name: material
  custom_dir: overrides
  language: pt
  features:
    - search.suggest
    - search.highlight
    - navigation.expand
  palette:
    scheme: default
  font:
    text: Inter
    code: JetBrains Mono

extra_css:
  - stylesheets/custom.css

extra:
  generator: false

copyright: "&copy; Grupo 16, Compiladores(T01)"

nav:
  - Home: index.md
  - Sobre: sobre.md
  - Documentação:
      - Escopo e Arquitetura: tech-docs/escopo-e-arq.md
  - Equipe: equipe.md
